### ISSUE TITLE
Feature: User can navigate to the factions page

### ISSUE THREAD

**Issue by AaronHe09** [AaronHe09/Unveiling-Ancient-Military-Might#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can browse thru a list of factions

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will press Factions in the nav bar and will be redirected to the factions page. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

- [ ] wrap BrowserRouter around the app component in index.js
- [ ] import routes and route in App.js
- [ ] add a route /factions to the factions component
- [ ] import link and outlet in NavBar.js
- [ ] in NavBar.js wrap factions in a link tag and link it to /factions
